INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411167,'Programação I', 1, 4, 'P I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411180,'Laboratório de Programação I', 1, 4, 'LP I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411311,'Fundamentos de Matemática para Ciência da Computação I', 1, 4, 'FMCC I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411174,'Introdução à Computação', 1, 4, 'IC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411312,'Fundamentos de Matemática para Ciência da Computação II', 2, 4, 'FMCC II')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1109126,'Cálculo Diferencial e Integral I', 2, 4, 'CI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411168,'Programação II', 2, 4, 'PII')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411181,'Laboratório de Programação II', 2, 4, 'LPII')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1109049,'Álgebra Linear', 3, 4, 'AL')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411304,'Teoria dos Grafos', 3, 4, 'TG')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1109131,'Cálculo Diferencial e Integral II', 3, 4, 'CII')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411172,'Estrutura de Dados', 3, 4, 'EDA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411179,'Laboratório de Estrutura de Dados', 3, 4, 'LEDA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411307,'Lógica para Computação', 3, 4, 'LC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1114129,'Introdução à Probabilidade', 4, 4, 'IP')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411308,'Projeto de Software', 4, 4, 'PSOFT')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411309,'Paradigmas de Linguagens de Programação', 4, 4, 'PLP')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411193,'Banco de Dados I', 4, 4, 'BDI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411310,'Organização e Arquitetura de Computadores', 4, 4, 'OAC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411182,'Laboratório de Organização e Arquitetura de Computadores', 4, 4, 'LOAC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1114222,'Estatística Aplicada', 5, 4, 'EA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411313,'Análise de Sistemas', 5, 4, 'AS')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411314,'Engenharia de Software', 5, 4, 'ES')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411190,'Redes de Computadores', 5, 4, 'RC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411192,'Sistemas Operacionais', 5, 4, 'SO')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411171,'Teoria da Computação', 5, 4, 'TC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411383,'Metodologia Científica', 6, 4, 'MC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411315,'Programação Concorrente', 6, 4, 'PC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411316,'Inteligência Artificial', 6, 4, 'IA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411187,'Análise e Técnicas de Algoritmos', 7, 4, 'ATAL')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411189,'Compiladores', 7, 4, NULL)
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411185,'Projeto em Computação I', 8, 4, 'PCI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1111111,'Projeto de Trabalho de Conclusão de Curso', 8, 4, 'PTCC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411348,'Projeto em Computação II', 9, 4, 'PCII')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411318,'Trabalho de Conclusão de Curso', 9, 4, 'TCC')

INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1305219,'Direito e Cidadania', 1, 4, 'DeC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1303021,'Economia', 1, 4, 'Economia')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1307150,'Inglês', 1, 4, 'TCC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1307332,'Libras', 1, 4, 'TCC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1307169,'Língua Portuguesa', 1, 4, 'LP')

INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1108030,'FÍSICA GERAL I', 6, 4, 'FG I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1108081,'FÍSICA GERAL II', 6, 4, 'FG II')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1108100,'FÍSICA GERAL III', 6, 4, 'FG III')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1108100,'FÍSICA GERAL IV', 6, 4, 'FG IV')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1109035,'ÁLGEBRA VETORIAL E GEOMETRIA ANALÍTICA', 6, 4, 'AVGA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1109128,'CÁLCULO DIFERENCIAL E INTEGRAL III', 6, 4, 'CIII')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1301123,'ADMINISTRAÇÃO E EMPREENDEDORISMO', 6, 4, 'ADM e Empreendedorismo')


INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411366,'Computação e Música', 6, 4, 'CeM')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411345,'Informática e Sociedade', 6, 4, 'InfoSoc')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411372,'Interface Humano-Computador', 6, 4, 'TCC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411333,'Prática de Ensino de Computação I', 2, 2, 'PEC I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411334,'Prática de Ensino de Computação II', 3, 2, 'PEC II')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411336,'Programação em Banco de Dados', 6, 4, 'PBD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411217,'Projeto de Redes de Computadores', 6, 4, 'PRC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411339,'Recuperação de Informação e Busca na Web', 6, 4, 'RI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411340,'Segurança de Sistema', 6, 4, 'SS')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411222,'Sistemas Distribuídos', 6, 4, 'SD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411343,'Verificação e Validação de Software', 6, 4, 'V&V')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411373,'Jogos Digitais', 6, 4, 'JD')

INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411188,'Métodos e Softwares Númericos', 6, 4, 'MSN')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411194,'Banco de Dados II', 6, 4, 'BD II')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411197,'AVALIAÇÃO DE DESEMPENHO DE SISTEMAS DISCRETOS', 6, 4, 'ADSD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411198,'ADMINISTRAÇÃO DE SISTEMAS GERENCIADORES DE BANCO DE DADOS', 6, 4, 'ADSGBD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411200,'COMPUTAÇÃO GRÁFICA', 6, 4, 'CG')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411213,'OTIMIZAÇÃO', 6, 4, 'Otimização')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411221,'SISTEMAS DE INFORMAÇÕES GEOGRÁFICAS', 6, 4, 'SIG')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411302,'TECC I (PROGRAMAÇÃO FUNCIONAL)', 6, 4, 'PF')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411320,'ADMINISTRAÇÃO DE SISTEMAS', 6, 4, 'ADM de Sist.')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411321,'ALGORITMOS AVANÇADOS I', 6, 4, 'AA I')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411322,'ALGORITMOS AVANÇADOS II', 6, 4, 'AA II')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411323,'ALGORITMOS AVANÇADOS III', 6, 4, 'AA III')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411324,'ALGORITMOS AVANÇADOS IV', 6, 4, 'AA IV')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411325,'ARQUITETURA DE SOFTWARE', 6, 4, 'Arquitetura de Software')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411326,'DESENVOLVIMENTO DE APLICAÇÕES CORPORATIVAS AVANÇADAS', 6, 4, 'DACA')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411327,'DESENVOLVIMENTO DE SOFTWARE INTEGRADO À OPERAÇÃO DA INFRAESTRUTURA', 6, 4, 'DSIOI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411328,'ECONOMIA DE TECNOLOGIA DA INFORMAÇÃO', 6, 4, 'ETI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411329,'EMPREENDEDORISMO EM SOFTWARE', 6, 4, 'EeS')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411330,'GERÊNCIA DE REDES', 6, 4, 'GR')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411331,'INTERCONEXÃO DE REDES DE COMPUTADORES', 6, 4, 'IRC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411332,'MÉTODOS FORMAIS', 6, 4, 'MF')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411335,'PRINCÍPIOS DE DESENVOLVIMENTO WEB', 6, 4, 'PDW')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411337,'PROVISIONAMENTO E OPERAÇÃO DE INFRAESTRUTURA', 6, 4, 'POI')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411338,'RECONHECIMENTO DE PADRÕES E REDES NEURAIS', 6, 4, 'RPRN')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411342,'SISTEMAS DE APOIO À DECISÃO', 6, 4, 'SAD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411344,'VISÃO COMPUTACIONAL', 6, 4, 'VC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411349,'TECC I (PROJETO DE SISTEMAS OPERACIONAIS)', 6, 4, 'PSO')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411350,'TECC I (GESTÃO DE PROJETOS)', 6, 4, 'GP')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411351,'TECC I (CIÊNCIA DE DADOS DESCRITIVA)', 6, 4, 'CDD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411352,'TECC I (PERCEPÇÃO COMPUTACIONAL)', 6, 4, 'PC')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411353,'TECC II (APLICAÇÕES DE TEORIA DOS GRAFOS)', 6, 4, 'ATG')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411354,'TECC II (APLICAÇÕES DE PARADIGMAS DE LINGUAGEM DE PROGRAMAÇÃO)', 6, 4, 'APLP')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411355,'TECC I (VISUALIZAÇÃO DE DADOS)', 6, 4, 'VD')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411356,'TECC I (CIÊNCIA DE DADOS PREDITIVA)', 6, 4, 'CDP')
INSERT INTO tb_disciplina (codigo_disciplina, nome_disciplina, num_periodo, quant_creditos, sigla) VALUES (1411357,'TECC I (GOVERNANÇA DA INTERNET)', 6, 4, 'GI')




