INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411167,'Programação I', 1, 4, 'PI')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411180,'Laboratório de Programação I', 1, 4, 'LPI')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411311,'Fundamentos de Matemática para Ciência da Computação I', 1, 4, 'FMCC I')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411174,'Introdução à Computação', 1, 4, 'IC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411312,'Fundamentos de Matemática para Ciência da Computação II', 2, 4, 'FMCC II')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1109126,'Cálculo Diferencial e Integral I', 2, 4, 'CI')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411168,'Programação II', 2, 4, 'PII')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411181,'Laboratório de Programação II', 2, 4, 'LPII')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1109049,'Álgebra Linear', 3, 4, 'AL')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411304,'Teoria dos Grafos', 3, 4, 'TG')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1109131,'Cálculo Diferencial e Integral II', 3, 4, 'CII')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411172,'Estrutura de Dados', 3, 4, 'EDA')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411179,'Laboratório de Estrutura de Dados', 3, 4, 'LEDA')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411307,'Lógica para Computação', 3, 4, 'LC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1114129,'Introdução à Probabilidade', 4, 4, 'IP')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411308,'Projeto de Software', 4, 4, 'PSOFT')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411309,'Paradigmas de Linguagens de Programação', 4, 4, 'PLP')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411193,'Banco de Dados I', 4, 4, 'BDI')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411310,'Organização e Arquitetura de Computadores', 4, 4, 'OAC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411182,'Laboratório de Organização e Arquitetura de Computadores', 4, 4, 'LOAC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1114222,'Estatística Aplicada', 5, 4, 'EA')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411313,'Análise de Sistemas', 5, 4, 'AS')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411314,'Engenharia de Software', 5, 4, 'ES')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411190,'Redes de Computadores', 5, 4, 'RC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411192,'Sistemas Operacionais', 5, 4, 'SO')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411171,'Teoria da Computação', 5, 4, 'TC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411383,'Metodologia Científica', 6, 4, 'MC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411315,'Programação Concorrente', 6, 4, 'PC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411316,'Inteligência Artificial', 6, 4, 'IA')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411187,'Análise e Técnicas de Algoritmos', 7, 4, 'ATAL')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411189,'Compiladores', 7, 4, NULL)
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411185,'Projeto em Computação I', 8, 4, 'PCI')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (NULL,'Projeto de Trabalho de Conclusão de Curso', 8, 4, 'PTCC')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411348,'Projeto em Computação II', 9, 4, 'PCII')
INSERT INTO tb_disciplina (codigoDisciplina, nomeDisciplina, numPeriodo, quantCreditos, sigla) VALUES (1411318,'Trabalho de Conclusão de Curso', 9, 4, 'TCC')



